server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/account/**
        - id: test-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/test/**, /api/v1/answer/**, /api/v1/resource/**, /api/v1/question/**
        - id: file-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/v1/file/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/Lingo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

idp:
  url: http://localhost:8180
  client-id: Lingo
  client-secret: JK7Mc23PlhXx3TSCVlC3wKhq7PmohD8I
  realm: Lingo

